name: Build and release version

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn kotlin:compile -B package --file pom.xml
  release:
    steps:
      uses: qcastel/github-actions-maven-release@master
      env:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        version-patch: true
        release-branch-name: "main"
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        maven-args: "-Dmaven.deploy.skip=true"
